#ifndef COMMONUTILITY_GLOBAL_H
#define COMMONUTILITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONUTILITY_LIBRARY)
#  define COMMONUTILITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONUTILITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONUTILITY_GLOBAL_H
